### PR TITLE
Optimize duplication checking code

### PR DESCRIPTION
**Pull request by alanrme**
Optimize code that checks if redirect is already an endpoint

### CODE REVIEW

**Comment by alecks** [comment]
This doesn't actually work; you're returning from the anonymous function.

**Comment by alanrme** [comment]
fu*ck

**Comment by htbrown** [comment]
Don't even need it tbh, this project is only simple.

**Comment by alanrme** [comment]
It is scientifically proven to be gay to not write efficient code.

**Comment by alecks** [comment]
I mean if you want to do it in the same way, just use something like

```js
if (
    app._router.stack.map(r => r.route ? r.route.path : null).includes(id)
) return;
```

**Pull request closed without merging**
